### ISSUE TITLE
Support qb:order for dimensions

### ISSUE THREAD

**Issue by ktk** [cpvrlab/sparql-table-viewer#24]
With https://github.com/lindas-uc/bafu_ubd/commit/975f475186229b5013a8582de59ae24cf672fc8b I've added `qb:order` to the Data Cube definition.

Please note that this is optional so the viewer should also work without.

**Comment by ktk** [comment]
For definitions see https://www.w3.org/TR/vocab-data-cube/#dfn-qb-order and https://www.w3.org/TR/vocab-data-cube/#dsd-dsd

**Comment by l00mi** [comment]
Integerated.
