### ISSUE TITLE
Produce links which download the current view in multiple formats.

### ISSUE THREAD

**Issue by l00mi** [cpvrlab/sparql-table-viewer#4]
http://test.lindas-data.ch/sparql?default-graph-uri=&query=select+distinct+*+where+%7B%3Fa+%3Fb+%3Fc+.+%7D+LIMIT+1000&should-sponge=&format=application%2Fsparql-results%2Bxml&timeout=0

**Comment by wacki** [comment]
This was added in f27d528e8fedc033a4bc00996ffc1ae3f1f7f42a.
However formats readable by the browser will of course not trigger a download prompt if we do it like this but will be rendered directly in the browser (ex.: html and json).
If a smooth user experience is the goal then we might want to look into something like this in the future:  https://github.com/johnculviner/jquery.fileDownload
